# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20171121_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
    ]
